Person crud
Laranto-spb/itechart-rails-course pull request #2
Opened 2021-12-09 11:38 UTC by Laranto-spb

Problems:
1. Rspec for People controller failed - CRUD
2. Rubocop problems with old syntax in rsec tests
3. Select form for people (home page) - how to get choice and route to show page of this person? Am I right that it means "choice person to track"?

2021-12-10 07:42 UTC, Laranto-spb commented on spec/requests/people_spec.rb
> +end
What is wrong here?

2021-12-10 08:10 UTC, Laranto-spb commented on spec/requests/people_spec.rb
> +      expect(Person.exists?(person1.id)).to be_falsey
It passed!!! Why check of  Person count does not work, but check if Person exist works?

2021-12-10 08:13 UTC, Laranto-spb commented on spec/requests/people_spec.rb
> -      expect(Person.count).to eq(0)
eq to 1 does not work also (

2021-12-10 15:23 UTC, e-popolamov commented on spec/requests/people_spec.rb
> +      expect(Person.exists?(person1.id)).to be_falsey
Cuz let() it's lazy initialization. 
`let(:person1)` and `let(:person2)` create user if in it block u call person1 or person2
Try in it block call person2.
for dirty example try 
```
  it 'delete person' do
      person2
      person1
      puts Person.all.count
      person1.destroy
      puts Person.all.count
      expect(Person.exists?(person1.id)).to be_falsey
    end

```
and puts return in first time `2` and second time `1`.
for pretty result use let!(:person) for create immediately.
https://mixandgo.com/learn/ruby/let-vs-let!

2021-12-10 15:29 UTC, e-popolamov commented
spec/requests/people_spec.rb failed. U create user with id and in second it he try to create user with existing id.
Also don't work delete person functionality. 
Please add more spec(for exmpl. for person model 'if name has more that 25 symbols or less than 2')
U can exclude spec folder from rubocop check.

2021-12-10 15:30 UTC, e-popolamov requested changes
Please make changes

2021-12-10 15:30 UTC, e-popolamov commented on app/controllers/people_controller.rb
> +    if current_user.people.count > 1
maybe better move this check to model level?

2021-12-10 15:30 UTC, e-popolamov commented on app/controllers/people_controller.rb
> +
Please remove empty lines

2021-12-10 15:30 UTC, e-popolamov commented on app/controllers/users/registrations_controller.rb
> +    # before_action :configure_sign_up_params, only: [:create]
this comments needed?

2021-12-11 08:03 UTC, Laranto-spb commented on app/controllers/users/registrations_controller.rb
> +    # before_action :configure_sign_up_params, only: [:create]
No) deleted

2021-12-11 08:03 UTC, Laranto-spb commented on app/controllers/people_controller.rb
> +
Corrected

2021-12-11 09:14 UTC, Laranto-spb commented on spec/models/person_spec.rb
> +    end
Added crud tests to model spec

2021-12-11 09:15 UTC, Laranto-spb commented on spec/requests/people_spec.rb
> +      expect(response).to have_http_status(:success)
Added test that list of user people exists

2021-12-11 09:26 UTC, Laranto-spb commented
People can be deleted from list
![image](https://user-images.githubusercontent.com/64079576/145671574-6ae83a9e-1409-4c34-8255-a00ca2cfad1e.png)
![image](https://user-images.githubusercontent.com/64079576/145671600-c3f64033-477e-4441-9da9-020a7fd22180.png)
I can not find this problem (

2021-12-12 09:55 UTC, Laranto-spb commented on app/controllers/people_controller.rb
>          format.html { render :new, status: :unprocessable_entity }
Can I use something like format.html { render :new, status: :unprocessable_entity, **alert.now: "Some text"** }

2021-12-12 09:56 UTC, Laranto-spb commented
Made changes ✔

2021-12-13 22:56 UTC, e-popolamov commented
You have some problem with rubocop. Please fix it. 
Also I don't know why your delete functionality is works. Because Turbolinks not work with UJS. 
https://github.com/hotwired/turbo-rails#compatibility-with-rails-ujs

Fix some specs
![Screenshot from 2021-12-14 01-51-30](https://user-images.githubusercontent.com/88551298/145902233-3c8dec3c-bea0-4029-ac81-ffdc8ff449d4.png)

2021-12-14 06:36 UTC, Laranto-spb commented on app/controllers/people_controller.rb
> +  end
Created before action for "create" method to prevent Metrics/AbcSize rubocop fail

2021-12-14 06:38 UTC, Laranto-spb commented on spec/models/person_spec.rb
> +      User.create(id: 2, name: 'User', email: 'user@mail.ru', password: '123456', password_confirmation: '123456')
Created unique id, because I've created anothoer User with this id in User model rspec

2021-12-15 07:29 UTC, e-popolamov approved these changes

2021-12-15 07:29 UTC, e-popolamov commented on spec/models/person_spec.rb
> +      expect { person1.destroy }.to change(Person, :count).by(-1)
user have only one person. and u have validation on model. 
this case valid?

2021-12-15 07:29 UTC, e-popolamov commented on app/models/person.rb
> +      throw(:abort)
```suggestion
      throw(:abort) if user.people.count <=1
```
better use one line

2021-12-15 07:29 UTC, merged